name: Transcript

on:
  workflow_dispatch:

jobs:
  bench:
    name: Bench Job
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Execution
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          export TOOL=faster
          export FRAMEWORK=gha
          source bin/test.sh samples/default.m4a

