name: Utranscript

on:
  workflow_dispatch:

jobs:
  bench:
    name: Bench Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Execution
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          FRAMEWORK=gha
          TOOL=faster
          bash bin/utest.sh samples/default.m4a

